// Code generated by MockGen. DO NOT EDIT.
// Source: internal/reservation/usecase/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/reservation/usecase/init.go -destination=_mock/usecase/mock_usecase.go -package=mockusecase
//

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	model "parkir-pintar/services/reservation/internal/reservation/model"
	apperror "parkir-pintar/services/reservation/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReservation is a mock of Reservation interface.
type MockReservation struct {
	ctrl     *gomock.Controller
	recorder *MockReservationMockRecorder
	isgomock struct{}
}

// MockReservationMockRecorder is the mock recorder for MockReservation.
type MockReservationMockRecorder struct {
	mock *MockReservation
}

// NewMockReservation creates a new mock instance.
func NewMockReservation(ctrl *gomock.Controller) *MockReservation {
	mock := &MockReservation{ctrl: ctrl}
	mock.recorder = &MockReservationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservation) EXPECT() *MockReservationMockRecorder {
	return m.recorder
}

// CreateReservation mocks base method.
func (m *MockReservation) CreateReservation(ctx context.Context, req model.CreateReservationRequest) (*model.CreateReservationResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservation", ctx, req)
	ret0, _ := ret[0].(*model.CreateReservationResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreateReservation indicates an expected call of CreateReservation.
func (mr *MockReservationMockRecorder) CreateReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservation", reflect.TypeOf((*MockReservation)(nil).CreateReservation), ctx, req)
}

// GetReservation mocks base method.
func (m *MockReservation) GetReservation(ctx context.Context, reservationID string) (*model.GetReservationResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservation", ctx, reservationID)
	ret0, _ := ret[0].(*model.GetReservationResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetReservation indicates an expected call of GetReservation.
func (mr *MockReservationMockRecorder) GetReservation(ctx, reservationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservation", reflect.TypeOf((*MockReservation)(nil).GetReservation), ctx, reservationID)
}
