// Code generated by MockGen. DO NOT EDIT.
// Source: /home/ermanur/dev/tech-assessment/ParkirPintar/reservation/pkg/paymentclient/client.go
//
// Generated by this command:
//
//	mockgen -source=/home/ermanur/dev/tech-assessment/ParkirPintar/reservation/pkg/paymentclient/client.go -destination=/home/ermanur/dev/tech-assessment/ParkirPintar/reservation/_mock/pkg/paymentclient/mock_paymentclient.go -package=mockpaymentclient -mock_names=PaymentService=MockPaymentService
//

// Package mockpaymentclient is a generated GoMock package.
package mockpaymentclient

import (
	context "context"
	paymentv1 "parkir-pintar/services/reservation/gen/payment/v1"
	apperror "parkir-pintar/services/reservation/pkg/apperror"
	paymentclient "parkir-pintar/services/reservation/pkg/paymentclient"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
	isgomock struct{}
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentService) CreatePayment(ctx context.Context, idempotencyKey, referenceID, driverID string, paymentType paymentv1.PaymentType, amountIDR int64) (*paymentclient.CreatePaymentResult, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, idempotencyKey, referenceID, driverID, paymentType, amountIDR)
	ret0, _ := ret[0].(*paymentclient.CreatePaymentResult)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentServiceMockRecorder) CreatePayment(ctx, idempotencyKey, referenceID, driverID, paymentType, amountIDR any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentService)(nil).CreatePayment), ctx, idempotencyKey, referenceID, driverID, paymentType, amountIDR)
}
