// Code generated by MockGen. DO NOT EDIT.
// Source: internal/reservation/repository/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/reservation/repository/init.go -destination=_mock/reservation/mock_repository.go -package=mockreservation
//

// Package mockreservation is a generated GoMock package.
package mockreservation

import (
	context "context"
	model "parkir-pintar/services/reservation/internal/reservation/model"
	apperror "parkir-pintar/services/reservation/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReservation is a mock of Reservation interface.
type MockReservation struct {
	ctrl     *gomock.Controller
	recorder *MockReservationMockRecorder
	isgomock struct{}
}

// MockReservationMockRecorder is the mock recorder for MockReservation.
type MockReservationMockRecorder struct {
	mock *MockReservation
}

// NewMockReservation creates a new mock instance.
func NewMockReservation(ctrl *gomock.Controller) *MockReservation {
	mock := &MockReservation{ctrl: ctrl}
	mock.recorder = &MockReservationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservation) EXPECT() *MockReservationMockRecorder {
	return m.recorder
}

// AcquireSpotLock mocks base method.
func (m *MockReservation) AcquireSpotLock(ctx context.Context, spotID, driverID string) (bool, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireSpotLock", ctx, spotID, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// AcquireSpotLock indicates an expected call of AcquireSpotLock.
func (mr *MockReservationMockRecorder) AcquireSpotLock(ctx, spotID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireSpotLock", reflect.TypeOf((*MockReservation)(nil).AcquireSpotLock), ctx, spotID, driverID)
}

// CreateReservationAndLockSpot mocks base method.
func (m *MockReservation) CreateReservationAndLockSpot(ctx context.Context, reservation *model.Reservation) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservationAndLockSpot", ctx, reservation)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreateReservationAndLockSpot indicates an expected call of CreateReservationAndLockSpot.
func (mr *MockReservationMockRecorder) CreateReservationAndLockSpot(ctx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservationAndLockSpot", reflect.TypeOf((*MockReservation)(nil).CreateReservationAndLockSpot), ctx, reservation)
}

// GetAvailableSpot mocks base method.
func (m *MockReservation) GetAvailableSpot(ctx context.Context, vehicleType model.VehicleType) (*model.Spot, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSpot", ctx, vehicleType)
	ret0, _ := ret[0].(*model.Spot)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetAvailableSpot indicates an expected call of GetAvailableSpot.
func (mr *MockReservationMockRecorder) GetAvailableSpot(ctx, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSpot", reflect.TypeOf((*MockReservation)(nil).GetAvailableSpot), ctx, vehicleType)
}

// GetByID mocks base method.
func (m *MockReservation) GetByID(ctx context.Context, id string) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReservationMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReservation)(nil).GetByID), ctx, id)
}

// GetByIdempotencyKey mocks base method.
func (m *MockReservation) GetByIdempotencyKey(ctx context.Context, key string) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockReservationMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockReservation)(nil).GetByIdempotencyKey), ctx, key)
}

// GetSpotByID mocks base method.
func (m *MockReservation) GetSpotByID(ctx context.Context, spotID string) (*model.Spot, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotByID", ctx, spotID)
	ret0, _ := ret[0].(*model.Spot)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetSpotByID indicates an expected call of GetSpotByID.
func (mr *MockReservationMockRecorder) GetSpotByID(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotByID", reflect.TypeOf((*MockReservation)(nil).GetSpotByID), ctx, spotID)
}

// HasActiveReservation mocks base method.
func (m *MockReservation) HasActiveReservation(ctx context.Context, driverID string) (bool, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveReservation", ctx, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// HasActiveReservation indicates an expected call of HasActiveReservation.
func (mr *MockReservationMockRecorder) HasActiveReservation(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveReservation", reflect.TypeOf((*MockReservation)(nil).HasActiveReservation), ctx, driverID)
}

// ReleaseSpotLock mocks base method.
func (m *MockReservation) ReleaseSpotLock(ctx context.Context, spotID string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseSpotLock", ctx, spotID)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// ReleaseSpotLock indicates an expected call of ReleaseSpotLock.
func (mr *MockReservationMockRecorder) ReleaseSpotLock(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseSpotLock", reflect.TypeOf((*MockReservation)(nil).ReleaseSpotLock), ctx, spotID)
}
