// Code generated by MockGen. DO NOT EDIT.
// Source: internal/reservation/repository/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/reservation/repository/init.go -destination=_mock/reservation/mock_repository.go -package=mockreservation -mock_names=Reservation=MockReservationRepository
//

// Package mockreservation is a generated GoMock package.
package mockreservation

import (
	context "context"
	model "parkir-pintar/services/reservation/internal/reservation/model"
	apperror "parkir-pintar/services/reservation/pkg/apperror"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}

// Exec mocks base method.
func (m *MockDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockDB) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDB)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDB)(nil).QueryRow), varargs...)
}

// MockReservationRepository is a mock of Reservation interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// AcquireSpotLock mocks base method.
func (m *MockReservationRepository) AcquireSpotLock(ctx context.Context, spotID, driverID string) (bool, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireSpotLock", ctx, spotID, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// AcquireSpotLock indicates an expected call of AcquireSpotLock.
func (mr *MockReservationRepositoryMockRecorder) AcquireSpotLock(ctx, spotID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireSpotLock", reflect.TypeOf((*MockReservationRepository)(nil).AcquireSpotLock), ctx, spotID, driverID)
}

// CancelReservationAndReleaseSpot mocks base method.
func (m *MockReservationRepository) CancelReservationAndReleaseSpot(ctx context.Context, reservationID, spotID string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelReservationAndReleaseSpot", ctx, reservationID, spotID)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// CancelReservationAndReleaseSpot indicates an expected call of CancelReservationAndReleaseSpot.
func (mr *MockReservationRepositoryMockRecorder) CancelReservationAndReleaseSpot(ctx, reservationID, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelReservationAndReleaseSpot", reflect.TypeOf((*MockReservationRepository)(nil).CancelReservationAndReleaseSpot), ctx, reservationID, spotID)
}

// ConfirmReservation mocks base method.
func (m *MockReservationRepository) ConfirmReservation(ctx context.Context, reservationID string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmReservation", ctx, reservationID)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// ConfirmReservation indicates an expected call of ConfirmReservation.
func (mr *MockReservationRepositoryMockRecorder) ConfirmReservation(ctx, reservationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmReservation", reflect.TypeOf((*MockReservationRepository)(nil).ConfirmReservation), ctx, reservationID)
}

// CreateReservationAndLockSpot mocks base method.
func (m *MockReservationRepository) CreateReservationAndLockSpot(ctx context.Context, reservation *model.Reservation) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservationAndLockSpot", ctx, reservation)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreateReservationAndLockSpot indicates an expected call of CreateReservationAndLockSpot.
func (mr *MockReservationRepositoryMockRecorder) CreateReservationAndLockSpot(ctx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservationAndLockSpot", reflect.TypeOf((*MockReservationRepository)(nil).CreateReservationAndLockSpot), ctx, reservation)
}

// ExpireReservationAndReleaseSpot mocks base method.
func (m *MockReservationRepository) ExpireReservationAndReleaseSpot(ctx context.Context, reservationID, spotID string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireReservationAndReleaseSpot", ctx, reservationID, spotID)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// ExpireReservationAndReleaseSpot indicates an expected call of ExpireReservationAndReleaseSpot.
func (mr *MockReservationRepositoryMockRecorder) ExpireReservationAndReleaseSpot(ctx, reservationID, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireReservationAndReleaseSpot", reflect.TypeOf((*MockReservationRepository)(nil).ExpireReservationAndReleaseSpot), ctx, reservationID, spotID)
}

// GetAvailableSpot mocks base method.
func (m *MockReservationRepository) GetAvailableSpot(ctx context.Context, vehicleType model.VehicleType) (*model.Spot, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSpot", ctx, vehicleType)
	ret0, _ := ret[0].(*model.Spot)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetAvailableSpot indicates an expected call of GetAvailableSpot.
func (mr *MockReservationRepositoryMockRecorder) GetAvailableSpot(ctx, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSpot", reflect.TypeOf((*MockReservationRepository)(nil).GetAvailableSpot), ctx, vehicleType)
}

// GetByID mocks base method.
func (m *MockReservationRepository) GetByID(ctx context.Context, id string) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReservationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReservationRepository)(nil).GetByID), ctx, id)
}

// GetByIdempotencyKey mocks base method.
func (m *MockReservationRepository) GetByIdempotencyKey(ctx context.Context, key string) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockReservationRepositoryMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockReservationRepository)(nil).GetByIdempotencyKey), ctx, key)
}

// GetExpiredReservations mocks base method.
func (m *MockReservationRepository) GetExpiredReservations(ctx context.Context) ([]model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredReservations", ctx)
	ret0, _ := ret[0].([]model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetExpiredReservations indicates an expected call of GetExpiredReservations.
func (mr *MockReservationRepositoryMockRecorder) GetExpiredReservations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredReservations", reflect.TypeOf((*MockReservationRepository)(nil).GetExpiredReservations), ctx)
}

// GetSpotByID mocks base method.
func (m *MockReservationRepository) GetSpotByID(ctx context.Context, spotID string) (*model.Spot, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotByID", ctx, spotID)
	ret0, _ := ret[0].(*model.Spot)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetSpotByID indicates an expected call of GetSpotByID.
func (mr *MockReservationRepositoryMockRecorder) GetSpotByID(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotByID", reflect.TypeOf((*MockReservationRepository)(nil).GetSpotByID), ctx, spotID)
}

// HasActiveReservation mocks base method.
func (m *MockReservationRepository) HasActiveReservation(ctx context.Context, driverID string) (bool, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveReservation", ctx, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// HasActiveReservation indicates an expected call of HasActiveReservation.
func (mr *MockReservationRepositoryMockRecorder) HasActiveReservation(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveReservation", reflect.TypeOf((*MockReservationRepository)(nil).HasActiveReservation), ctx, driverID)
}

// ReleaseSpotLock mocks base method.
func (m *MockReservationRepository) ReleaseSpotLock(ctx context.Context, spotID string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseSpotLock", ctx, spotID)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// ReleaseSpotLock indicates an expected call of ReleaseSpotLock.
func (mr *MockReservationRepositoryMockRecorder) ReleaseSpotLock(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseSpotLock", reflect.TypeOf((*MockReservationRepository)(nil).ReleaseSpotLock), ctx, spotID)
}
