// Code generated by MockGen. DO NOT EDIT.
// Source: internal/reservation/usecase/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/reservation/usecase/init.go -destination=_mock/reservation/mock_usecase.go -package=mockreservation -mock_names=Reservation=MockReservationUsecase
//

// Package mockreservation is a generated GoMock package.
package mockreservation

import (
	context "context"
	model "parkir-pintar/services/reservation/internal/reservation/model"
	apperror "parkir-pintar/services/reservation/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReservationUsecase is a mock of Reservation interface.
type MockReservationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockReservationUsecaseMockRecorder
	isgomock struct{}
}

// MockReservationUsecaseMockRecorder is the mock recorder for MockReservationUsecase.
type MockReservationUsecaseMockRecorder struct {
	mock *MockReservationUsecase
}

// NewMockReservationUsecase creates a new mock instance.
func NewMockReservationUsecase(ctrl *gomock.Controller) *MockReservationUsecase {
	mock := &MockReservationUsecase{ctrl: ctrl}
	mock.recorder = &MockReservationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationUsecase) EXPECT() *MockReservationUsecaseMockRecorder {
	return m.recorder
}

// CreateReservation mocks base method.
func (m *MockReservationUsecase) CreateReservation(ctx context.Context, req model.CreateReservationRequest) (*model.CreateReservationResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservation", ctx, req)
	ret0, _ := ret[0].(*model.CreateReservationResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreateReservation indicates an expected call of CreateReservation.
func (mr *MockReservationUsecaseMockRecorder) CreateReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservation", reflect.TypeOf((*MockReservationUsecase)(nil).CreateReservation), ctx, req)
}

// GetReservation mocks base method.
func (m *MockReservationUsecase) GetReservation(ctx context.Context, reservationID string) (*model.GetReservationResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservation", ctx, reservationID)
	ret0, _ := ret[0].(*model.GetReservationResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetReservation indicates an expected call of GetReservation.
func (mr *MockReservationUsecaseMockRecorder) GetReservation(ctx, reservationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservation", reflect.TypeOf((*MockReservationUsecase)(nil).GetReservation), ctx, reservationID)
}

// HandleBookingPaymentDone mocks base method.
func (m *MockReservationUsecase) HandleBookingPaymentDone(ctx context.Context, reservationID, status string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBookingPaymentDone", ctx, reservationID, status)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// HandleBookingPaymentDone indicates an expected call of HandleBookingPaymentDone.
func (mr *MockReservationUsecaseMockRecorder) HandleBookingPaymentDone(ctx, reservationID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBookingPaymentDone", reflect.TypeOf((*MockReservationUsecase)(nil).HandleBookingPaymentDone), ctx, reservationID, status)
}
